### ISSUE TITLE
Issue with deserializing public key and signature

### ISSUE THREAD

**Issue by domwoe** [herumi/bls#101]
we are trying to verify a BLS signature from the [Internet Computer](https://internercomputer.org) with herumi/bls using the [C#](https://github.com/edjCase/BLS/blob/main/Test.cs) and [JS/WASM](https://github.com/domwoe/bls-test/blob/main/index.js) wrappers. See the links for example projects/tests.

However, deserialization of the public key and signature fails. 

In the code of a [Rust verification library to verify BLS signatures from the Internet Computer](https://docs.rs/ic-verify-bls-signature/0.1.0/src/ic_verify_bls_signature/lib.rs.html#22-54), there's the following comment:

```
/// The signature must be exactly 48 bytes (compressed G1 element)
/// The key must be exactly 96 bytes (compressed G2 element)
```

Is there any way to verify these signatures with herumi?

**Comment by herumi** [comment]
Sorry for the late response.
You call `blsSetETHserialization(1);` once after calling `blsInit`.

**Comment by herumi** [comment]
And you may have to call `mclBnG1_setDst`.

**Comment by herumi** [comment]
mclBnG1_setDst is not provided for C#/WASM, so I'll append it later. What generator ofG2 is?

**Comment by herumi** [comment]
It works when initialized as follows.
https://github.com/herumi/bls/commit/57b8da02bfc7883f5f09c7dea6c39dd55e55e234

**Comment by domwoe** [comment]
Thanks a lot, @herumi. Do you know if the C# and Go wrappers provide everything that is needed?

**Comment by herumi** [comment]
Now I've added a sample for C#.
https://github.com/herumi/bls/commit/88defaabc6eb471b933b67af091dd2834541e097

**Comment by herumi** [comment]
I've added a sample for Go.
https://github.com/herumi/bls-go-binary/commit/d496a2684849e627d4f1c0a0a138159c1ac30ac0

**Comment by herumi** [comment]
The Wasm version.
- [add settings](https://github.com/herumi/bls-wasm/commit/32c2c511dafe294fbfebc1cb9b6126bee3e7cf08)
- [sample](https://github.com/herumi/bls-wasm/commit/7810072cbf4b9386cac0328b13cbdcb6f933bf66)

**Comment by Gekctek** [comment]
Thank you! I have been working with @domwoe  and  I have confirmed that this solution works

**Comment by domwoe** [comment]
Thank you a lot @herumi!
