### ISSUE TITLE
How to build bls to run on different kinds cpu?

### ISSUE THREAD

**Issue by moonfruit** [herumi/bls#11]
I found that a built `bls` and `mcl` library sometimes panic on another computer, even they all are linux,amd64.

I do some research on this. I found that different cpu support for different `Cpu::Type`, and I found that `xbyak` do test these flags. I think maybe `xbyak` generate different codes because of different `Cpu::Type`.

So if I want build a library that run on different computers, may I should disable `xbyak` through `MCL_USE_XBYAK=0 make`, am I right?

If I disable `xbyak`, how much impact on performance? Is there a way to use `xbyak` in a general enough way?

**Comment by herumi** [comment]
>may I should disable xbyak through MCL_USE_XBYAK=0 make, am I right?

yes, it is an option for mcl. It may be about 10~20% worse performance.

>Is there a way to use xbyak in a general enough way?
I test mcl for several CPUs and it runs well.
Could you tell me what kind of errors and CPU?

I noticed that I use -march=native option in common.mk, which generates an optimized code by compiler for host cpu and it does not run on the other cpu. Could you try remove the option?

**Comment by moonfruit** [comment]
I removed `-march=native` option from mcl/common.mk, and recompiled `mcl` and `bls`.
And it worked even with `xbyak`, thank you very much!
