### ISSUE TITLE
Trusted setup required for threshold signatures?

### ISSUE THREAD

**Issue by iljah** [herumi/bls#16]
As far as I can tell, currently the only way to create threshold keys is to call `set(const SecretKeyVec& msk, const Id& id)` of SecretKey class which requires all partial secret keys to be passed in as argument. Is it possible to use this library to create threshold keys in a way that no one participating in threshold setup knows all initial secret keys (`msk` above)?

**Comment by herumi** [comment]
Sorry for the very late reply.
I missed seeing this issue.

What you want may be DKG(distributed key generation).
One easy way is that each user calls getMasterSecretKey
and sends secret key to others.
And each user aggregates the secret keys.
But there are many points to consider.
That is out of the scope of this library.

* [Secure Distributed Key Generation for Discrete-Log Based Cryptosystems](https://link.springer.com/content/pdf/10.1007%2F3-540-48910-X_21.pdf)
* https://github.com/dfinity/dkg

**Comment by iljah** [comment]
Thanks, I think this is what DASH folks are also/will be [using](https://blog.dash.org/secret-sharing-and-threshold-signatures-with-bls-954d1587b5f).

**Comment by herumi** [comment]
Yes, they sent a [PR](https://github.com/herumi/bls/pull/13) before and I added some primitive APIs.
Maybe they will construct what they need with these APIs.
