### ISSUE TITLE
Support building from an installed mcl in any $(prefix) location

### ISSUE THREAD

**Issue by infinity0** [herumi/bls#17]
Currently the bls build depends on mcl but it is hard-coded it look for it in `../`. This means it is hard to package for package managers like Debian or Nix.

It would be good if bls could just find mcl in the normal system directories. Usually if a dependency is installed there (e.g. `/usr/include`) then you don't even need to give any `-I` or `-l` flags.

**Comment by herumi** [comment]
Sorry for the very late reply.
I forgot this issue.

The souce of mcl is necessary to build bls, so I added `MCL_DIR`.
How about it?

https://github.com/herumi/bls/commit/e9d5952ea046f29896329068e16f9526eddef04c

**Comment by infinity0** [comment]
It should not be necessary to use the source of mcl to build bls, only the headers. Can we add a `CMakeLists.txt` to this repository? This sequence of steps should Just Work out-of-the-box:

```
mcl.git$ rm -rf build && mkdir build && cd build
mcl.git$ cmake ..
mcl.git$ make
mcl.git$ sudo make install
mcl.git$ cd ../bls.git
bls.git$ rm -rf build && mkdir build && cd build
bls.git$ cmake ..
bls.git$ make
bls.git$ sudo make install
```

At the end, we should have a `/usr/local/lib/libbls256.so` and `/usr/local/lib/libbls384.so`. This is required for nix integration.

**Comment by infinity0** [comment]
If you can describe in high-level how `mcl.git/common.mk` works and why the bls `Makefile` requires it, I can then help figure out how to write a `CMakeLists.txt` for this bls library.

**Comment by herumi** [comment]
>It should not be necessary to use the source of mcl to build bls, only the headers.

Yes, that's right. But it is necessary to build bls library by historical reason and backward compatibility.

https://github.com/herumi/bls/blob/dev/CMakeLists.txt runs well if you put mcl and bls in the same directory and I add -DMCL_DIR=<mcl source path> option if necessary.

How about this?

**Comment by infinity0** [comment]
> https://github.com/herumi/bls/blob/dev/CMakeLists.txt runs well if you put mcl and bls in the same directory and I add -DMCL_DIR= option if necessary.
> 
> How about this?

This is problematic:

~~~~
include_directories(
	${MCL_DIR}/src ./include/
)
~~~~

Why is it not possible to remove the `${MCL_DIR}/src` part? How can we fix this?

**Comment by herumi** [comment]
>Can we expose bn_c_impl.hpp as a public include-header of mcl? Or split it into a public and private part, expose the public part, and use #include bn_c_public.hpp here in bls.git?

Yes, now I am about to do it now.

**Comment by infinity0** [comment]
Thanks! 7a36e06984f98153e8b27f5d82603fb7d1227cc8 fixes this issue.
