### ISSUE TITLE
support bn256 and bn384 build tags in the go bindings

### ISSUE THREAD

**Issue by siva0chain** [herumi/bls#20]
The mcl library go bindings provide build tag to choose bn256 or bn384 as part of building the go library. However, the bls go bindings only default to bn384. See the cgo headers of

https://github.com/herumi/mcl/blob/master/ffi/go/mcl/mcl.go
vs
https://github.com/pmer/gobls/blob/master/bls.go
https://github.com/pmer/gobls/blob/master/mcl.go

**Comment by herumi** [comment]
I added the option https://github.com/herumi/bls/commit/f63e122a2cff8d0e20288b897c449a42cdf84897 .
But this requires tags. Do you know how to set default tag(bn384)?

**Comment by herumi** [comment]
>Do you know how to set default tag(bn384)?

I support no tag for backward compatibility. https://github.com/herumi/bls/commit/e17ebfd57bcc6b97d7012811527fbad93952f655

**Comment by siva0chain** [comment]
Thank you
