### ISSUE TITLE
Question About Using Project in Go Package

### ISSUE THREAD

**Issue by rauljordan** [herumi/bls#22]
Hi @herumi,

Looks like the efficiency drop isn't too bad without GMP (barely noticeable), but we have another consideration. We plan on wrapping this project in a go wrapper called https://github.com/prysmaticlabs/go-bls which people can then import and use in their own projects through a `go get github.com/prysmaticlabs/go-bls`. We don't want our users to need to know much about its internals, they should just be able to `go get` and have it working.

The problem is that your system working relies on people running make to generate the static and shared object libraries, which are architecture dependent. Do you suggest then just precompiling these libraries for all major architectures and checking them into the `lib/` folder to distribute? Is this a security concern?

Additionally, on Ubuntu, the tests expect me to have the lib in $LD_LIBRARY_PATH so I have to `export LD_LIBRARY_PATH=mcl/lib:$LD_LIBRARY_PATH` which we do not want people to need to do all the time. Do you have recommendations to get around this?

**Comment by moonfruit** [comment]
I have build a similar project at https://github.com/moonfruit/bls for use `bls` in go.
I built static libraries for linux,amd64, darwin,amd64 and windows,amd64.
I think they are enough for mostly scenes.

**Comment by herumi** [comment]
@rauljordan 

> Do you suggest then just precompiling these libraries for all major architectures and checking them into the lib/ folder to distribute? Is this a security concern?

What should I do? Would you distribute the necessary pre-built binaries?

@moonfruit 

>I also changed the go code for bls a little bit for more go-style.

I'll see your modification. bls.go is my first Go programming, so I have to study more.

**Comment by avive** [comment]
@rauljordan - I think that the issue is a bit more involved - I believe that cgo is architecture dependent.  So, any dependency that uses c libs (such as any go wrapper around this bls lib) needs to be compiled on the target platform as it uses the native g++ compiler that is used in the toolchain. See: https://dave.cheney.net/2016/01/18/cgo-is-not-go

**Comment by LeoHChen** [comment]
https://github.com/harmony-one/harmony is using the bls library as well.  we have to fork it in our repo and distribute the libraries anyway.  Unless there is a native go implementation of bls, I don't if there is a solution. If anyone knows, let us know as well.

**Comment by herumi** [comment]
If you want to cgo linking static library, then you build an only static library as @moonfruit  says. (if a shared library exists in the same directory, then it is used with priority.)

I add minimised_static to make only libbls384_256.a at https://github.com/herumi/bls/commit/8845290fd98a2f3bec3e9bc2adafdcaddb82ec8a .
The sample code is in https://github.com/herumi/bls/tree/dev/ffi/go
The sample binary depends only standard libraries.
