### ISSUE TITLE
Feature suggestion: support for using go crypto/rand PRNG

### ISSUE THREAD

**Issue by avive** [herumi/bls#26]
It looks like the library is using /dev/urandom as a PRNG on linux platforms.
Allow go clients to provide the go crypto/rand generator for the library as a configuration option so there's more control over the PRNG used. See: https://golang.org/pkg/crypto/rand/ . The library currently support providing a c PRNG function. One way to implement this feature is to wrap crypto/rand in a compatible c function and provide it to the library.

**Comment by herumi** [comment]
I'm sorry that I could not understand your intention.
Does it mean to call `mclBn_setRandFunc` with `crypto/rand`?
`crypto/rand` calls `/dev/urandom/`, too then it seems the same result.
What is the configuration option?

https://github.com/herumi/mcl/blob/master/include/mcl/bn.h#L231

**Comment by avive** [comment]
I believe that on linux crypto/rand is using getrandom(2) if it is available and /dev/urandom otherwise. Ref: https://golang.org/src/crypto/rand/rand.go?s=799:837

**Comment by herumi** [comment]
I see. By the way, I have not called Go functions from C.
Do you know any good reference about it?

**Comment by herumi** [comment]
I found https://golang.org/cmd/cgo/#hdr-C_references_to_Go .

**Comment by herumi** [comment]
It took a long time to understand how to call Go-functions from C.
How about [SetRandFunc](https://github.com/herumi/bls/commit/3900a6ec637be56529972e17553e2b301832da46#diff-5c5383a471fd128dfb2b95aa6966080cR476) ?

**Comment by moonfruit** [comment]
I create a sha.go to replace openssl's sha implement with go implement.
That might be some inspiration for using go's crypto/rand.

https://github.com/moonfruit/bls/blob/master/sha.go

**Comment by herumi** [comment]
@moonfruit 
Thank you for the code.
Could you tell me the reason for using not OpenSSL but Go implementation?
