### ISSUE TITLE
Hello herumi, I have a question about Secret Sharing API

### ISSUE THREAD

**Issue by Senlody** [herumi/bls#3]
In this part, it's said that  f(x) = msk[0] + msk[1] x + ... + msk[k-1] x^{k-1}, where msk[0] is the original secret key s. Does it mean that every member of the group is able to generate the final signature sH(m) without collecting signature of other members?

**Comment by herumi** [comment]
The only system setup knows msk[0].
He uses `void SecretKey::set(const SecretKeyVec& msk, const Id& id);` and sends `f(id)` to each user.
see https://en.wikipedia.org/wiki/Shamir%27s_Secret_Sharing

**Comment by Senlody** [comment]
Thanks for reply, I have a further question: If none of the members in the group is trusted by everyone, then who will setup the sharing?

**Comment by herumi** [comment]
Under the situation, use DKG(https://en.wikipedia.org/wiki/Distributed_key_generation).

**Comment by Senlody** [comment]
Thanks a lot, it's clear now.
