### ISSUE TITLE
print public key got inconsistent result in go

### ISSUE THREAD

**Issue by LeoHChen** [herumi/bls#30]
I am using go-binding of bls in harmony-one/harmony project. I was trying to compare two public keys by checking the print out value in the log file.  However, I found two public keys print out different values in string format even though they are deserialized from the same byte array.

I guess it is because the bls go-binding didn't implement the String function for golang.

**Comment by herumi** [comment]
What curve do you use and could you show me the value of public keys?

I test serialization at https://github.com/herumi/bls/blob/master/ffi/go/bls/bls_test.go#L264-L273 and it runs well.
