### ISSUE TITLE
Build bls in MSYS2 / mingw64

### ISSUE THREAD

**Issue by tzcytpm** [herumi/bls#33]
Hi Herumi, 

I tried to build bls under MSYS2 / MinGW64, but I couldn't build. I got many errors like that: `include/mcl/fp.hpp:330: undefined reference to `mcl::fp::copyAndMask(unsigned long long*, void const*, unsigned long long, mcl::fp::Op const&, mcl::fp::MaskMode)' `

I used: make MCL_USE_LLVM=0 INTEL=0 MCL_USE_GMP=1 MCL_USE_OPENSSL=0

I read this article, and it is possible to build bls in MSYS2: https://github.com/herumi/bls/issues/7

Could you help me?

Thanks in advance.

**Comment by herumi** [comment]
What is your intention?
Do you want to use it with GMP and without OpenSSL?
Is the reason for `MCL_USE_LLVM=0 INTEL=0`?

I test mcl and bls on Mingw64 and `env PATH=$PATH:lib make MCL_USE_OPENSSL=0 test_ci` runs well.

```
$ uname -a
MINGW64_NT-10.0-17763 kaby 3.0.6-338.x86_64 2019-04-15 06:44 UTC x86_64 Msys
```

**Comment by tzcytpm** [comment]
Thank you so much, Herumi, 
With your instruction I could build mcl successfull. But for bls I've met a different error with the Makefile:
`Makefile:46: *** target pattern contains no '%'.  Stop.`

my environment:
'$ uname -a
MINGW64_NT-10.0 DESKTOP-LQ58ECB 3.0.6(0.338/5/3) 2019-04-15 06:44 x86_64 Msys'

Thanks.

**Comment by herumi** [comment]
mcl and bls must be the same directory as the followings:

```
work/
  /mcl
  /bls
```

or specify the `mcl` directory by `make MCL_DIR=<mcl directory>`.

**Comment by tzcytpm** [comment]
Yeah, I put them in the same directory:
```
build/
/bls
/mcl
```
I built bls in Ubuntu, MacOSX, and everything is well. Only there is a problem with Windows.

**Comment by herumi** [comment]
Hum, it runs well on my environment.

Makefile:46 is
```
$(MCL_LIB):
	$(MAKE) -C $(MCL_DIR)
```
so, it does not contain %.

How about `make -C ../mcl ../mcl/lib/libmcl.a`?

**Comment by tzcytpm** [comment]
I tried with your command, but it is not worked. But if I changed the path to the folder libmcl.a, it worked:
```
tzcytpm@DESKTOP-LQ58ECB MINGW64 ~/build/bls
$ make -C ../mcl ../mcl/lib/libmcl.a
make: Entering directory '/home/tzcytpm/build/mcl'
make: *** No rule to make target '../mcl/lib/libmcl.a'.  Stop.
make: Leaving directory '/home/tzcytpm/build/mcl'
```

But it will work: 
```
tzcytpm@DESKTOP-LQ58ECB MINGW64 ~/build/bls
$ make -C ../mcl lib/libmcl.a
make: Entering directory '/home/ntrung/build/mcl'
g++ -D__USE_MINGW_ANSI_STDIO=1 -g3 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith -m64 -I include -I test -fomit-frame-pointer -DNDEBUG -Ofast  -fPIC -c src/fp.cpp -o obj/fp.o -MMD -MP -MF obj/fp.d
ar r lib/libmcl.a obj/fp.o
C:\msys64\mingw64\bin\ar.exe: creating lib/libmcl.a
```
So Should I modify the Makefile in bls?
Thanks.

**Comment by herumi** [comment]
In the top of bls/Makefile, I modify PWD for MINGW64.
If changing it to `PWD=$(shell pwd)` then does `make` run well?

**Comment by tzcytpm** [comment]
I tried, but it still didn't work:
```
tzcytpm@DESKTOP-LQ58ECB MINGW64 ~/build/bls
$ env PATH=$PATH:lib make MCL_USE_OPENSSL=0
Makefile:8: /home/tzcytpm/build/bls/mcl/common.mk: No such file or directory
make: *** No rule to make target '/home/tzcytpm/build/bls/mcl/common.mk'.  Stop.
```

**Comment by herumi** [comment]
```
/home/tzcytpm/build/bls/mcl/common.mk: No such file or directory
```
It is wrong. It should be `/home/tzcytpm/build/mcl/common.mk`.
I do not know why seeking the path.

How about this?
```
make MCL_USE_OPENSSL=0 MCL_DIR=/home/tzcytpm/build/bls/
```

**Comment by tzcytpm** [comment]
Hi Herumi,
In the end I could build with changing path to:
`PWD=$(shell pwd)`
Thanks so much for your help.

**Comment by herumi** [comment]
Thank you for your report.

Maybe the following command runs well without changing Makefile.
```
 make MCL_DIR=`pwd`/../mcl/
```

**Comment by herumi** [comment]
I fixed it. but `make test_go` still fails on /home/... . I do not know how to fix it. (it runs well on /c/... ). I suspect it is a bug of cgo on mingw.
