### ISSUE TITLE
Is there a way to make this work for the secp256k1 curve?

### ISSUE THREAD

**Issue by jorisoudejans** [herumi/bls#37]
For the purpose of generating shares of an Ethereum private key, would it be possible to make this work for the secp256k1 curve? And if so, how would I go about doing that?

**Comment by herumi** [comment]
I'm sorry that I've lost this issue.

We can't use secp256k1 for BLS-signature by mathematical reason.
So you can't use this library for it.

**Comment by jorisoudejans** [comment]
Hi, no problem, I figured that one out some time after posting this issue. Thanks for the reply!
