### ISSUE TITLE
bls/src/bls_c_impl.hpp:457:3: error: ‘millerLoopVec’ was not declared in this scope

### ISSUE THREAD

**Issue by xcshuan** [herumi/bls#40]
I want to compile bls from sourcecode, so I ran commands as follow:
````
cd bls
mkdir build & cd build
cmake ..
make
````

but, I got error:
millerLoopVec(e2, g1Vec, g2Vec, m);
   ^~~~~~~~~~~~~
Is a bug or my misoperation?

**Comment by herumi** [comment]
The error may be caused by the old mcl.
Could you try `cd mcl && git pull && cd ../bls` and rebuild bls?

**Comment by xcshuan** [comment]
> The error may be caused by the old mcl.
> Could you try `cd mcl && git pull && cd ../bls` and rebuild bls?

You are right, thx.
