### ISSUE TITLE
Is it safe to reuse same key for diff message ? 

### ISSUE THREAD

**Issue by patrickkh7788** [herumi/bls#42]
This is a question not a bug report.  (don't know where to ask so I put it here)

for BLS12-381:

When I use G2 as public key, (minimizing signature size),  is it safe use the same private key to signature a lot message ? (each message with a unique message id, so they are all different),  the message quantity could be billion and still safe without leak private key ?

I read from blockchain document, the minimizing public key size variant use G1 as public key(48 byte),  G2 as signatures(48 byte), and private key is 32 byte.  So I guess the minimizing signature size public key size is 96byte, signature is 48 byte,  private key still 32 byte,  is this correct ?

**Comment by herumi** [comment]
>When I use G2 as public key, (minimizing signature size), is it safe use the same private key to signature a lot message ?

Yes. BLS signature is secure under co-DHP, and the hash function is a random oracle.

My default bls library uses G2 as a public key and G1 as a signature. If you defined BLS_ETH, then my library uses G1 as a public key and G2 as a signature.

BLS12_381|private key|public key|signature|
-|-|-|-|
default|Fr|G2|G1|
BLS_ETH|Fr|G1|G2|

where Fr=32, G1=48, G2=96

**Comment by patrickkh7788** [comment]
Thanks for the explain.

Is any random 32 byte number is valid private key ?

**Comment by herumi** [comment]
If the curve is BLS12-381, then every value in [0, r) is valid where r = 0x240026400f3d82b2e42de125b00158405b710818ac000007e0042f008e3e00000000001080046200000000000000000d.

**Comment by patrickkh7788** [comment]
Thanks again for the explain. 

Is BLS12_381 valid private key total quantity around 2^32( BN381 around 2^48)?  or a much smaller number like 2^16? 

What I worry about is it possible to build a huge static dictionary,  can search private key by public key?  for example my system share billion public key to internet,  then maybe few private key can be search from public key ?

**Comment by patrickkh7788** [comment]
r = `0x240026400f3d82b2e42de125b00158405b710818ac000007e0042f008e3e00000000001080046200000000000000000d` is 48 byte,  Fr is 32 byte.   I am confuse the relation about `r` and `Fr`. that is why I ask you again for the total valid `Fr` quantity for BLS12-381

**Comment by herumi** [comment]
I'm sorry to miss to copy the value.
The correct value is r = `0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001`.
Please see [api.md](https://github.com/herumi/mcl/blob/master/api.md#curve-parameter).
