### ISSUE TITLE
Support DESTDIR in makefile

### ISSUE THREAD

**Issue by daurnimator** [herumi/bls#45]
Please support `DESTDIR` for `make install`. https://www.gnu.org/prep/standards/html_node/DESTDIR.html

Note that currently you have `PREFIX`: traditionally that is lowercase and used to construct variables `libdir`, `includedir` and others:

```makefile
prefix ?= /usr/local
includedir ?= $(prefix)/include
libdir ?= $(prefix)/lib
datadir ?= $(prefix)/share

INSTALL ?= install
INSTALL_DATA ?= $(INSTALL) -m 644
```

**Comment by herumi** [comment]
Is [this patch](https://github.com/herumi/bls/commit/853ea3a74e406cdedef03820cd3f3d959b7dea36) is what you want?

**Comment by daurnimator** [comment]
> Is [this patch](https://github.com/herumi/bls/commit/853ea3a74e406cdedef03820cd3f3d959b7dea36) what you want?

Yes :)
Would you also consider using `$(INSTALL)`  and `$(INSTALL_DATA)` instead of `cp -a`?

**Comment by herumi** [comment]
I used them. https://github.com/herumi/bls/commit/721d0228378aace7ec590808710e727d63320190
