### ISSUE TITLE
How do we compile for Android platforms?

### ISSUE THREAD

**Issue by muruguru** [herumi/bls#54]
Hi,

I am trying to build for Android platforms (armv7-a, 8a, x86) and don't see instructions for building it. Do you have any instructions to build as libraries?

Thanks

**Comment by herumi** [comment]
Please see https://github.com/herumi/bls-eth-go-binary#android .

**Comment by muruguru** [comment]
Thanks @herumi . I tried to build a .so on android and I am able to load the library, but in x86_64, when I call blsSecretKeySetByCSPRNG or blsIdGetHexStr, I am seeing a SIGSEGV (Signal: SIGSEGV (signal SIGSEGV: invalid address (fault address: 0x0)))

Do you have any suggestions on how to fix it?

**Comment by muruguru** [comment]
@herumi . Please discard my previous message. I figured out the problem. I had set the wrong DMCLBN_FP_UNIT_SIZE bit value

**Comment by bartwell** [comment]
> I tried to build a .so on android and I am able to load the library

Hello @muruguru, could you please provide some information how did you achieve this? What is the way to build libbls384_256.a into *.so library?

**Comment by uszkaisandor** [comment]
> able to load the library, but in x86_64, when I call blsSecretKeySetByCSPRNG or blsIdGetHexStr, I am seeing a SIGSEGV (Signal: SIGSEGV (signal SIGSEGV

@muruguru 
How could you build this? I got only .o and .a files instead of .so file. Did I forgot a step?

**Comment by herumi** [comment]
I added an option to build so.
https://github.com/herumi/bls-eth-go-binary/commit/2bdbdadbf8bb883e5b42664c136c2e30329635a8

```
cd bls-eth-go-binary
make -j android BLS_LIB_SHARED=1
```
