### ISSUE TITLE
blsSecretKeySetByCSPRNG(&sec) not loading

### ISSUE THREAD

**Issue by Raycoms** [herumi/bls#55]
Hi,

I included the bls and mcl library in my project

```
#include <iostream>
#include <mcl/bn_c384_256.h>
#include <bls.h>
#include <mcl/bn.h>
#include <mcl/curve_type.h>

using namespace std;

int main()
{
    cout << "Hello, World!" << endl;

    blsInit(MCL_BLS12_381, MCLBN_COMPILED_TIME_VAR);

    blsSetETHmode(BLS_ETH_MODE_LATEST);

    blsSecretKey sec;
    blsPublicKey pub;

    // init SecretKey sec by random number
    cout << blsSecretKeySetByCSPRNG(&sec) << endl;
    // get PublicKey pub from SecretKey sec
    blsGetPublicKey(&pub, &sec);

    blsSignature sig;
    char msg[] = "hello";
    const size_t msgSize = strlen(msg);

    blsSign(&sig, &sec, msg, msgSize);
    
    // return 1 if it is valid else 0
    cout <<  blsVerify(&sig, &pub, msg, msgSize) << endl;
    return 0;
}
```

And tried to execute the examples, however, the program stops at blsSecretKeySetByCSPRNG
(Doesn't return any value and doesn't continue executing afterwards either)

**Comment by Raycoms** [comment]
Some extra news, I was able to find out it is getting a "segmentation fault" on this call: blsSecretKeySetByCSPRNG

**Comment by herumi** [comment]
It is necessary to define `-DBLS_ETH=1` to use `blsSetETHmode(BLS_ETH_MODE_LATEST);`.

```
make lib/libbls384_256.a BLS_ETH=1
g++ sample/minsample.c -DBLS_ETH=1 -I ./include/ -I ../mcl/include/ lib/libbls384_256.a -lgmp -lgmpxx ../mcl/lib/libmcl.a
```

**Comment by Raycoms** [comment]
Even if I remove the line: blsSetETHmode(BLS_ETH_MODE_LATEST); it runs into the segmentation fault. (I also tried with the BLS_ETH=1 flag, same result).

**Comment by herumi** [comment]
Could you tell me your OS, CPU, compiler, and compiler options?
Maybe `blsInit` returns non zero.

Is the result of the command in https://github.com/herumi/bls/issues/55#issuecomment-632590540 okay?

**Comment by Raycoms** [comment]
Linux version 5.4.40-1-MANJARO (builder@3a0c57f97980) (gcc version 9.3.0 (Arch Linux 9.3.0-1)) #1 SMP PREEMPT Sun May 10 14:17:40 UTC 2020

I'm using cmake 3.17.2 (running it within CLion).

No additional compiler options.

**Comment by herumi** [comment]
Please make `libbls384_256.a` by not cmake but `make clean && make BLS_ETH=1`.
`CMakefile.txt` does not support `BLS_ETH` option. I'll append it later.

**Comment by Raycoms** [comment]
Okay, I tried that. Making worked. But when I include it into my project now.

![image](https://user-images.githubusercontent.com/6438347/82682656-823f0280-9c47-11ea-9fdc-ce2ace640082.png)

I still get the segmentation fault. (However, now it shows me exactly where it ran into it).

**Comment by herumi** [comment]
>I still get the segmentation fault.

No function can be called if `blsInit` fails. You should always check the return value of `blsInit`.

>This here resulted in -244046 as the output value of blsInit

This shows that mismatch of compiler option between library and your code. There are libbls384_256.a built without BLS_ETH=1.
Please remove all `/usr/local/lib/libbls*` and try to use libbls384_256.a built with BLS_ETH=1.

**Comment by Raycoms** [comment]
> > I still get the segmentation fault.
> 
> No function can be called if `blsInit` fails. You should always check the return value of `blsInit`.
> 

The method call that fails is "blsSecretKeySetByCSPRNG" and not blsInit, blsInit and blsSetEthmode execute well (seemingly), what fails then is the creation of the secret key.

> > This here resulted in -244046 as the output value of blsInit
> 
> This shows that mismatch of compiler option between library and your code. There are libbls384_256.a built without BLS_ETH=1.
> Please remove all `/usr/local/lib/libbls*` and try to use libbls384_256.a built with BLS_ETH=1.

I did that again as well, I scrapped all the old ones and replaced them with a fresh build. I even setup a new project and it resulted in the same outcome.

**Comment by herumi** [comment]
Does the command
```
make BLS_ETH=1 bin/bls_c384_256_test.exe && bin/bls_c384_256_test.exe
``` 
run well on your system?
It runs well on [Travis-ci](https://travis-ci.org/github/herumi/bls) and contins a test of [`blsSecretKeySetByCSPRNGS`](https://github.com/herumi/bls/blob/master/test/bls_c_test.hpp#L25-L40).

**Comment by Raycoms** [comment]
```
g++ obj/bls_c384_256_test.o -o bin/bls_c384_256_test.exe lib/libbls384_256.a -L/home/projects/bls/../mcl/lib -lmcl -lrt -lgmp -lgmpxx  -m64 
bin/bls_c384_256_test.exe: error while loading shared libraries: libmcl.so: cannot open shared object file: No such file or directory
```

Which is weird, because in home/projects/bls/../mcl/lib that specific file does exist.

**Comment by herumi** [comment]
Sorry, please specify LD_LIBRARY_PATH.

```
env LD_LIBRARY_PATH=../mcl/lib bin/bls_c384_256_test.exe
```

**Comment by Raycoms** [comment]
Yes,

that runs

```
ctest:module=all
i=0
FrSize=32, FpSize=32
sign 275.435Kclk
verify   1.003Mclk
i=1
FrSize=32, FpSize=48
sign   1.049Mclk
verify   2.922Mclk
ctest:name=bls_c384_256_test, module=1, total=148, ok=148, ng=0, exception=0
```

**Comment by herumi** [comment]
Then, the setting of your project may have something wrong.
Please check once again whether BLS_ETH=1 is defined.
[static library](https://github.com/herumi/bls-eth-go-binary/tree/master/bls/lib/linux/amd64) is easier to use than dynamic library.

**Comment by Raycoms** [comment]
Yeah, I'm including it as a static library via cmake, hence why I'm so confused its not working.

I'm putting the library and header files into my library folder and then I load them from there.
So BLS_ETH=1 should not be strictly needed since I'm not generating new files, right?

**Comment by herumi** [comment]
`-DBLS_ETH=1` is always necessary before including `bls/bls.h`.

**Comment by Raycoms** [comment]
```
set(CMAKE_CXX_STANDARD 14)
set(ENV{DBLS_ETH} "1")

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake")

set(SOURCE_FILES src/main.cpp)
add_executable(blsbench ${SOURCE_FILES})

include(FindPkgConfig)
find_package(bls REQUIRED)
include_directories(${BLS_INCLUDE_DIR})
target_link_libraries(${PROJECT_NAME} ${BLS_LIBRARY})

find_package(mcl REQUIRED)
include_directories(${MCL_INCLUDE_DIR})
target_link_libraries(${PROJECT_NAME} ${MCL_LIBRARY})
```

I put it in the cmake file and that didn't really help.

**Comment by herumi** [comment]
Could you try not `set(ENV{DBLS_ETH} "1")` but addintg `#define BLS_ETH` to the source code before inclusing `bls.h`?
And I've updated `CMakefile.txt` to support "-DBLS_ETH=1" at the commit https://github.com/herumi/bls/commit/a750a3b1fd5718e6e494c27a8767a0cba42b3780 .

**Comment by Raycoms** [comment]
```
#include <iostream>
#include <mcl/bn_c384_256.h>

#define BLS_ETH = 1

#include <bls.h>
#include <mcl/curve_type.h>
```

Okay, this actually did work.
