### ISSUE TITLE
K out of N

### ISSUE THREAD

**Issue by Raycoms** [herumi/bls#56]
It's running fairly fine now including aggregation.
However, I could not find the function to check if k out n signed the aggregate.
(The blsAggregateSignature and blsFastAggregateVerify need exactly n)

**Comment by herumi** [comment]
The sample of k-of-n signature is only for C++
[k_of_nTest](https://github.com/herumi/bls/blob/master/test/bls_test.hpp#L147).

The corresponding C apis are https://github.com/herumi/bls/blob/master/include/bls/bls.h#L168-L173

1. make shared secret key from mask (master secret key) by `blsSecretKeyShare`.
1. each user makes public key from the shared secret key.
1. each user signs a message and make shared signature.
1. recover master signature by `blsSignatureRecover`.

**Comment by Raycoms** [comment]
BLS_DLL_API int blsSecretKeyShare(blsSecretKey *sec, const blsSecretKey* msk, mclSize k, const blsId *id);

I believe mclSize k is the long k (out of n)?
and blsId, is whose Id?

**Comment by Raycoms** [comment]
Wait, I understood it partially now.

I call this for each of the n ids to generate a partial key for its specific int id.

**Comment by Raycoms** [comment]
That worked
