### ISSUE TITLE
Timeline On Updating To V4 Ietf Draft  

### ISSUE THREAD

**Issue by nisdas** [herumi/bls#63]
The current IETF draft has been updated to V4 here:
https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-04

The relevant PR for it:
https://github.com/cfrg/draft-irtf-cfrg-bls-signature/pull/26 

The main change would be disallowing `SK==0` , so as to prevent the possibility of infinite pubkeys from occurring. 

Is this change planned anytime soon ?

**Comment by herumi** [comment]
Okay. I think that it is better to implement the modification in bls-eth-go-binary.

**Comment by herumi** [comment]
I made the issue at https://github.com/herumi/bls-eth-go-binary/issues/29

**Comment by nisdas** [comment]
Thanks !
