### ISSUE TITLE
How to compile bls and linked with cgo on windows?

### ISSUE THREAD

**Issue by moonfruit** [herumi/bls#7]
We know that cgo only support for gcc, and bls need to be compiled with cl on windows.
How can i use cgo to compile `bls` to a single one binary executable program?
I compiled `bls` into a `lib` with mklib.bat, but i cannot use cgo to link this.
How can i do?

**Comment by herumi** [comment]
[cgo](https://github.com/golang/go/wiki/cgo#windows) seems to require mingw-w64 and gcc.
[cmd/link: support msvc object files](https://github.com/golang/go/issues/20982)
I have not used cgo on Windows so I need time to study it.

**Comment by moonfruit** [comment]
Yes, I installed mingw-w64 gcc to use cgo. And I also installed Visual Studio Build Tools and Windows SDK to build bls.

I tried build `bls` with Visual Studio Build Tools to `lib`, but when i use cgo to link this a lot error occurred.

cgo flags:

```
#cgo CFLAGS:-I${SRCDIR}/include -DMCLBN_FP_UNIT_SIZE=6
#cgo windows,amd64 LDFLAGS:-L${SRCDIR}/lib/windows/amd64 -lbls384 -lmcl -llibeay32 -lmpir -lmpirxx
```

[link-lib-errors.txt](https://github.com/herumi/bls/files/2207910/link-lib-errors.txt)

And I also tried build `bls` with mingw-w64 gcc. I use command `make MCL_USE_LLVM=0 INTEL=0` to ignore asm, and it successfully build `libbls384.a` and `libmcl.a`. These `.a` can be linked to a single binary executable program with cgo. But when I `go test`, it panic...

cgo flags:

```
#cgo CFLAGS:-I${SRCDIR}/include -DMCLBN_FP_UNIT_SIZE=6
#cgo windows,amd64 LDFLAGS:-L${SRCDIR}/lib/windows/amd64 -lbls384 -lmcl -lcrypto -lgmp -lgmpxx -lstdc++
```

[link-a-error.txt](https://github.com/herumi/bls/files/2207916/link-a-error.txt)

Do you have any suggestions about this?

**Comment by herumi** [comment]
bls supports cgo on [msys2](https://sourceforge.net/projects/msys2/) now.

**Comment by moonfruit** [comment]
It's worked! Thanks a lot!
