### ISSUE TITLE
How to perform point subtraction and negation on BLS curve?

### ISSUE THREAD

**Issue by Qiao-Jin** [herumi/bls#76]
Hello! I'm curious how to perform point subtraction and negation on BLS curve.
I.e there are two signatures A and B, how to perform point subtraction & negation such as A - B, -B, etc in this repo? Thx!

--------

I observed that this func might be used for signature subtraction:

https://github.com/herumi/bls/blob/3f3850a6eac71e1ce31b4a3d9b85aa7af2a2d08e/src/bls_c_impl.hpp#L859

Could you please include this func into https://github.com/herumi/bls/blob/master/ffi/cs/bls.cs? Thx!

**Comment by Qiao-Jin** [comment]
@herumi

**Comment by herumi** [comment]
Do you want the function from C#?

**Comment by Qiao-Jin** [comment]
> Do you want the function from C#?

Yes, it's needed for subtraction between signatures

**Comment by herumi** [comment]
Okay, I'll append it. Please wait a moment.

**Comment by Qiao-Jin** [comment]
> Okay, I'll append it. Please wait a moment.

Thx so much!

**Comment by herumi** [comment]
I added sub methods.
https://github.com/herumi/bls/commit/98140f3d8efe2d7b99ca971461a0a99d08304903

Though `neg(X)` can be achieved using `sub(zero, X)`, do you need `neg`?

**Comment by Qiao-Jin** [comment]
> I added sub methods.
> [98140f3](https://github.com/herumi/bls/commit/98140f3d8efe2d7b99ca971461a0a99d08304903)
> 
> Though `neg(X)` can be achieved using `sub(zero, X)`, do you need `neg`?

I think that should be enough, thx!
By the way, if B = 3A, is there a way to get A from B?

**Comment by herumi** [comment]
What are the types of A and B?

**Comment by Qiao-Jin** [comment]
> What are the types of A and B?

They are signatures

**Comment by herumi** [comment]
I'm sorry for the late response. I added them about one month ago.
