### ISSUE TITLE
Bug report: Signature verification failure

### ISSUE THREAD

**Issue by Qiao-Jin** [herumi/bls#77]
**Problem**: 

Signature verification failure

**Steps to reproduce:**

1. Generate 4 private keys p1, p2, p3, p4
2. Calculate corresponding public keys P1, P2, P3, P4
3. Calculate aggregate private key p = p1 + 7 * p2 + 49 * p3 + 343 * p4
4. Calculate aggregate public key P = P1 + 7 * P2 + 49 * P3 + 343 * P4
5. Use p to sign a message and verify it with P

**Expected:**

Verification pass.

**Observed:**

Verification failed.

**Comment by Qiao-Jin** [comment]
@herumi

**Comment by herumi** [comment]
What code do you test?

**Comment by Qiao-Jin** [comment]
> What code do you test?

bls384_256

**Comment by Qiao-Jin** [comment]
And when using only P1, P2, P3 the verification result will be correct:

Steps:

1. Generate 4 private keys p1, p2, p3
2. Calculate corresponding public keys P1, P2, P3
3. Calculate aggregate private key p = p1 + 7 * p2 + 49 * p3
4. Calculate aggregate public key P = P1 + 7 * P2 + 49 * P3
5. using p to sign a message and verify it with P

**Comment by Qiao-Jin** [comment]
@herumi Could you please do a test locally to verify this result?

**Comment by herumi** [comment]
I don't know how to compute `49 * P3` and so on, but the following goes well.
So I wonder that your code has something wrong.

```
package main

import (
    "fmt"
    "github.com/herumi/bls-eth-go-binary/bls"
)

func main() {
    bls.Init(bls.BLS12_381)
    n := 4
    secs := make([]bls.SecretKey, n)
    pubs := make([]bls.PublicKey, n)
    sigs := make([]bls.Sign, n)
    msg := []byte("abcdefg")
    g1vec := make([]bls.G1, n)
    g2vec := make([]bls.G2, n)
    for i := 0; i < n; i++ {
        secs[i].SetByCSPRNG()
        pubs[i] = *secs[i].GetPublicKey()
        sigs[i] = *secs[i].SignByte(msg)
        fmt.Printf("sec[%v]=%s\n", i, secs[i].SerializeToHexStr())
        g1vec[i] = *bls.CastFromPublicKey(&pubs[i])
        g2vec[i] = *bls.CastFromSign(&sigs[i])
    }
    vs := make([]bls.Fr, n)
    for i := 0; i < n; i++ {
        vs[i].SetInt64(int64(i * i + 5))
    }
    var P bls.PublicKey
    bls.G1MulVec(bls.CastFromPublicKey(&P), g1vec, vs)
    var Q bls.Sign
    bls.G2MulVec(bls.CastFromSign(&Q), g2vec, vs)
    fmt.Printf("verify=%v\n", Q.VerifyByte(&P, msg)) // show true
}
```

**Comment by Qiao-Jin** [comment]
> I don't know how to compute `49 * P3` and so on, but the following goes well.
> So I wonder that your code has something wrong.

I use func blsPublicKeyAdd 49 times for this multiplication:
https://github.com/herumi/bls/blob/3f3850a6eac71e1ce31b4a3d9b85aa7af2a2d08e/src/bls_c_impl.hpp#L601

**Comment by Qiao-Jin** [comment]
And maybe you can try this coefficient vector [1, 7, 49, 343], it seems that the sum of the coefficients can affect verification result

**Comment by Qiao-Jin** [comment]
It seems in your code you generate the aggregate signature with signatures. And in my code it's got from aggregated private keys...

**Comment by Qiao-Jin** [comment]
It seems that I got some wrong logic in my code. I will reopen this if error still exists after correction.

**Comment by herumi** [comment]
@Qiao-Jin 
I've added MulVec method, so you can use it. https://github.com/herumi/bls/blob/master/ffi/cs/bls_test.cs#L215-L233
