### ISSUE TITLE
Is bls thread-safe?

### ISSUE THREAD

**Issue by moonfruit** [herumi/bls#8]
Is bls thread-safe to use same curve to sign or verify concurrently?
Is bls thread-safe to use different curve to sign or verify concurrently?

**Comment by herumi** [comment]
`blsInit` to change curve parameter is not thread safe.
sign/verify and other operations are thread safe after blsInit is complete.

**Comment by moonfruit** [comment]
When I `blsInit` one curve, I can thread-safe use all the API to sign or verify.
But if I want to use another curve, I should `blsInit` the one.
And all the API worked under the new curve, and if I want to use the previous one, I should `blsInit` the previous one again.
It means that `bls` does not support to use different curve at **the same time**.
Am I right?

**Comment by moonfruit** [comment]
OK, I get it, thank you!
