### ISSUE TITLE
NuGet package of C# binding

### ISSUE THREAD

**Issue by colibrishin** [herumi/bls#90]
https://github.com/planetarium/bls-herumi/tree/master/ffi/cs

After some struggle, have done some modifications in C# binding for cross-platform. Would it be okay to publish in a NuGet package? and could you help me with what `Id` is used for, and how the `Share/Recover[Type]()` methods work?

_Originally posted by @colibrishin in https://github.com/herumi/bls/issues/86#issuecomment-1217524601_

**Comment by herumi** [comment]
Thank you for the PR, but it contains many modifications, so it will take time to check it.

I'm not familiar with NuGet.
It seems that `.diea,` `NativeImprot`, and other added files look to be automatically generated. Are they necessary, or can we remove them?

**Comment by colibrishin** [comment]
For NuGet, [this](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli) might be helpful. Compiling native runtime and publishing NuGet package could be automated with Github Action (with [Publish NuGet](https://github.com/marketplace/actions/publish-nuget))

`.idea` is generated by _JetBrain Rider_, therefore it can be removed, however, `NativeImport` is needed for importing the native runtime.

**Comment by herumi** [comment]
I have some questions.

- How did you build files in runtimes?
- Are you planning to maintain the GitHub repository and a NuGet package?

https://github.com/planetarium/bls-herumi/blob/master/ffi/cs/Properties/AssemblyInfo.cs#L8-L12
I think that `bls-eth` is better than `bls256`.

**Comment by herumi** [comment]
>could you help me with what Id is used for, and how the Share/Recover[Type]() methods work?

`Id` is a public identifier to distinguish each user, so they should be different from each other.

Id means the `x_i` at https://en.wikipedia.org/wiki/Shamir%27s_Secret_Sharing#Mathematical_formulation .

**Comment by colibrishin** [comment]
> How did you build files in runtimes?

The POSIX builds are built with the following [Github Action](https://github.com/planetarium/bls-herumi/actions/runs/2880203837). And for Windows, I've used the mklib.bat with MSVC (vcvars64.bat.)

> Are you planning to maintain the GitHub repository and a NuGet package?

Yes, Within a range of BSD 3-Clause.

> https://github.com/planetarium/bls-herumi/blob/master/ffi/cs/Properties/AssemblyInfo.cs#L8-L12
> I think that bls-eth is better than bls256.

Thanks! I'll fix it.

**Comment by herumi** [comment]
>The POSIX builds are built with the [Github Action](https://github.com/planetarium/bls-herumi/actions/runs/2880203837).

Thank you for the information. I'll study it.

>>Are you planning to maintain the GitHub repository and a NuGet package?
>Yes.

I see. Which do you like whether the plan or the other one that I make a repository such as herumi/bls-eth-cs for NuGet and receive your PR?

**Comment by colibrishin** [comment]
> I see. Which do you like whether the plan or the other one that I make a repository such as herumi/bls-eth-cs for NuGet and receive your PR?

I have no insight about which is better. I'm planning to manage it with cherry-picking. What advantage would it offer to have a separate repository?

**Comment by herumi** [comment]
>What advantage would it offer to have a separate repository?

I don't want to put the DLL directly into the herumi/bls repository. If I can only put the DLL into the NuGet package, that's ok.

**Comment by herumi** [comment]
If you would not like to take the time to these discussions, you can feel free to publish a NuGet package from your repository.

**Comment by colibrishin** [comment]
I'll stay with publishing NuGet package from forked repository. Thanks for your help!
