### ISSUE TITLE
Question about API for k-of-n threshold signature

### ISSUE THREAD

**Issue by p2p-sergey-y** [herumi/bls#94]
Hello!
It's not really issue, more a question. 
In "API for k-of-n threshold signature" section the first action is `Prepare k secret keys (msk)`. 
After some test I realized that the first key is the real master key which will be divided and others are more like "entropy" for polynomial/shares. So what is the reason to create them by ourself, what not to provide just one master key, but other parameters generate randomly?

**Comment by herumi** [comment]
Yes.
https://en.wikipedia.org/wiki/Shamir%27s_Secret_Sharing#Mathematical_formulation

The secret key is $a_0$, and the other random values are $a_1, ..., a_{k-1}$.
